---
apiVersion: v1
kind: Namespace
metadata:
  name: shopping-list
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: shopping-list
    role: web
  name: shopping-list-svc
  namespace: shopping-list
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: http
  selector:
    app: shopping-list
    role: web
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: shopping-list
    role: web
  name: shopping-list-sa
  namespace: shopping-list
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shopping-list
    role: web
  name: shopping-list-web
  namespace: shopping-list
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping-list
      role: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: shopping-list
        role: web
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/csci335-spring23-381720/shopping-list/shopping-list-k8s:latest
        imagePullPolicy: Always
        name: shopping-list-web
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
      restartPolicy: Always
      serviceAccountName: shopping-list-sa
