version: "3.8"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env.development
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: shopping-list:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.development
    ports:
      - 5000:5000
    depends_on:
      - db

volumes:
  db_data: {}
